java_test(
    name = "TrivialLawTest",
    srcs = ["TrivialLawTest.java"],
    resources = [
        "//src/test/resources:trivial_law",
    ],
    deps = [
        "//src/main/java/edu/rutgers/moses/lawtester:test_agent",
        "//third_party:moses",
        "@junit//jar",
    ],
)

java_test(
    name = "PingpongLawTest",
    srcs = ["PingpongLawTest.java"],
    resources = [
        "//src/test/resources:pingpong_law",
    ],
    deps = [
        "//src/main/java/edu/rutgers/moses/lawtester:test_agent",
        "//third_party:moses",
        "@junit//jar",
    ],
)

java_test(
    name = "MonitorLawTest",
    srcs = ["MonitorLawTest.java"],
    resources = [
        "//src/test/resources:monitor_law",
    ],
    deps = [
        "//src/main/java/edu/rutgers/moses/lawtester:test_agent",
        "//third_party:moses",
        "@junit//jar",
    ],
)
