package(default_visibility = ["//visibility:public"])

filegroup(
    name = "trivial_law",
    srcs = [
        "trivial.law",
    ],
)

filegroup(
    name = "pingpong_law",
    srcs = [
        "pingpong.law",
    ],
)

filegroup(
    name = "monitor_law",
    srcs = [
        "monitor.law",
    ],
)
