package(default_visibility = ["//visibility:public"])

filegroup(
    name = "dummy_law",
    srcs = [
        "dummy.law",
    ],
)

filegroup(
    name = "trivial_law",
    srcs = [
        "trivial.law",
    ],
)

filegroup(
    name = "pingpong_law",
    srcs = [
        "pingpong.law",
    ],
)

filegroup(
    name = "monitor_law",
    srcs = [
        "monitor.law",
    ],
)

filegroup(
    name = "trivial_lawtest",
    srcs = [
        "trivial.lawtest",
    ],
)

filegroup(
    name = "pingpong_lawtest",
    srcs = [
        "pingpong.lawtest",
    ],
)

filegroup(
    name = "monitor_lawtest",
    srcs = [
        "monitor.lawtest",
    ],
)
